[package]
name = "light_evm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.8"
crossterm = "0.26.1"
hex = "0.4.3"

[[bin]]
name = "light_evm"
path = "src/main.rs"
